name: genx
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - awscli
  - abricate
  - barrnap
  - fastqc
  - fasttree
  - kraken2  
  - mauve
  - mauvealigner    
  - megahit 
  - mlst  
  - pip  
  - python=3
  - prinseq  
  - prokka  
  - quast  
  - roary  
  - spades
  - sickle-trim  
  - pip:
      - numpy
      - matplotlib
      - matplotlib-venn
      - biopython
      - dREP
